終了機能の追加とコンフリクトの解消
s1f102200952/django-test-exercise pull request #16
Opened 2023-07-13 05:22 UTC by s1f10220102

終了機能の追加とコンフリクトの解消をしました。

2023-07-18 00:31 UTC, s1f102200952 requested changes
修正依頼

2023-07-18 14:02 UTC, s1f10220102 commented
エラー部分の訂正

2023-07-19 01:58 UTC, s1f102200952 approved these changes

2023-07-19 01:59 UTC, s1f102200952 approved these changes
変更を承認します

2023-07-19 02:02 UTC, s1f102200952 approved these changes
承認

2023-07-20 02:23 UTC, closed without merging